`5`がコンソール出力される。

1. tryブロックで例外がスローされ、catchブロックに移動
1. catchブロックにはbreak文が記述されているが、forループを終了する前にまずはfinallyブロックの文を実行する
1. finallyブロックにはcontinue文が記述されているので、iをインクリメントしてtest式を再テストしてtrueならfor文をもう一度実行する
